In [8]:
import pandas as pd
from pathlib import Path
from datetime import date, timedelta

# 00 - Criando um DataFrame

In [2]:
data = {
    "id": list(range(1, 11)),
    "value": [10.5, 20.1, 30.2, 40.8, 50.0, 60.3, 70.7, 80.9, 90.4, 100.6],
    "name": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    "active": [True, False, True, True, False, True, False, True, False, True],
    "date": [date(2024, 1, 1) + timedelta(days=i) for i in range(10)]
}

In [3]:
df = pd.DataFrame(data)
df

   id  value name  active        date
0   1   10.5    A    True  2024-01-01
1   2   20.1    B   False  2024-01-02
2   3   30.2    C    True  2024-01-03
3   4   40.8    D    True  2024-01-04
4   5   50.0    E   False  2024-01-05
5   6   60.3    F    True  2024-01-06
6   7   70.7    G   False  2024-01-07
7   8   80.9    H    True  2024-01-08
8   9   90.4    I   False  2024-01-09
9  10  100.6    J    True  2024-01-10

In [5]:
# tipos das colunas
df.dtypes

id          int64
value     float64
name       object
active       bool
date       object
dtype: object

In [6]:
# filtros básicos
df[df['active'] == True]

   id  value name  active        date
0   1   10.5    A    True  2024-01-01
2   3   30.2    C    True  2024-01-03
3   4   40.8    D    True  2024-01-04
5   6   60.3    F    True  2024-01-06
7   8   80.9    H    True  2024-01-08
9  10  100.6    J    True  2024-01-10

In [7]:
df.query('value > 50')

   id  value name  active        date
5   6   60.3    F    True  2024-01-06
6   7   70.7    G   False  2024-01-07
7   8   80.9    H    True  2024-01-08
8   9   90.4    I   False  2024-01-09
9  10  100.6    J    True  2024-01-10

# 01 - Lendo um Arquivo

In [9]:
FILE_PATH = Path('data/data_raw.csv')
df = pd.read_csv(FILE_PATH)
df.head()

,sales,customer_id,customer_age,purchase_date,product,last_purchase_date,price,seller_id
0,52,1511,86,2024-10-07,Laptop,2022-05-29,2534.07,199
1,93,4985,52,2023-12-10,Smartphone,2023-09-20,1879.78,182
2,15,3092,69,2024-01-06,TV,2022-07-06,4844.32,112
3,72,4179,31,2023-02-02,Smartphone,2022-01-20,4705.96,147
4,61,3266,80,2024-01-09,Tablet,2023-01-08,4766.52,159